### PR TITLE
Implements the reciprocal scaling

### LINKED ISSUE #139: Implement reciprocal scaling
Reciprocal scaling is `x := x/alpha`, where x is an array. This operation is, in most cases, preferable to more `x := (1/alpha)*x`. For instance, the former has less accumulation error.

The technical report on the BLAS Standard, https://netlib.org/blas/blast-forum/blas-report.pdf, proposes the reciprocal scaling to be part of the BLAS. The current LAPACK code has its implementation of RSCL, but it relies on applying the BLAS SCAL to (1/alpha). MKL, for instance, has its own implementation of RSCL.

I think we should have a tlapack::rscl. I can propose the PR. Also, I can propose the PR in LAPACK++ so we can access code from MKL and other optimized libraries.

### PR DESCRIPTION
**Pull request by weslleyspereira**
Closes #139.

### CODE REVIEW

**Review by langou — COMMENTED** [review]
Nice!

**Comment by langou** [comment]
Maybe propagate to:
https://github.com/tlapack/tlapack/blob/0377a585a2e15653e4e6006a4aae53297b7f3ba6/include/tlapack/lapack/getrf_level0.hpp#L92

**Comment by langou** [comment]
Here then:
https://github.com/tlapack/tlapack/blob/0377a585a2e15653e4e6006a4aae53297b7f3ba6/include/tlapack/lapack/getrf_recursive.hpp#L102

**Comment by weslleyspereira** [comment]
> Here then:
> 
> https://github.com/tlapack/tlapack/blob/0377a585a2e15653e4e6006a4aae53297b7f3ba6/include/tlapack/lapack/getrf_recursive.hpp#L102

This was done in 3d947adc339102ff8771497828904e3eac8b16e2

**Comment by langou** [comment]
Excellent then!

**Comment by weslleyspereira** [comment]
[90496b7](https://github.com/tlapack/tlapack/pull/178/commits/90496b79cad1c91678be4022dca0d470bcee7b38) fixes an issue created by the new implementation.

The current implementation of `rscl` has two behaviors:
1. If `alpha` is real, then `x[i] /= alpha`.
2. If `alpha` is complex, then call `scal(real_type<alpha_t>(1) / alpha, x)`.

**Comment by weslleyspereira** [comment]
I am putting this as a draft since we are still missing the scaling of `1/alpha` when alpha is complex.

**Comment by weslleyspereira** [comment]
That is the current design of the algorithm I propose:

If alpha is real, then this routine is equivalent to scal(1/alpha, x). This
is done without overflow or underflow as long as the final result x/a does
not overflow or underflow.

If alpha is complex, then we use the following algorithm:
1. If the real part of alpha is zero, then we scale by the reciprocal of
the imaginary part of alpha.
2. If not, see if either real or imaginary part is greater than safeMax. If
so, do proper scaling.
3. If not, we can compute the reciprocal of real and imaginary parts of
1/alpha without NaNs. If both components are in the safe range, then we can
do the reciprocal without overflow or underflow. Otherwise, we scale by the
safe range.

**Comment by weslleyspereira** [comment]
In the following, I present two matrices and use LAPACK's getf2 to factorize them. We compare getf2 in LAPACK 3.11 with getf2 using the new RSCL we propose in this PR.

1. Take the matrix:
```fortran
A = [  b+i  1  ]
    [  b    b  ]
```

For this matrix, LU with pivoting does not permute the row for this matrix and its exact LU factorization is 
```fortran
L = [  1      0 ]       U = [  b+i   1       ]
      [  l21   1  ]              [  0      u22  ]
```
where 
```
 l21 = b / (b + i )
 u22 = b / (b+i) * ( b+i-1 )
```

2. Now, let us use floating-point arithmetic and set `b` as a large number for this aritmetic. For example, let us use single precision and `b = 2^75`.

In this case, LAPACK's getf2 using the inline seven-line reciprocal scaling algorithm returns the factorization:
```
L = [  1      0 ]       U = [  b+i   1   ]
      [  1       1 ]              [  0      b  ]
```
whereas the new reciprocal scaling algorithm
```
L = [  1          0 ]       U = [  b+i   1   ]
      [  l21       1 ]              [  0      b  ]
```
The relative error is very small: 1.528233e-23, so no problems here. No problems because the condition number is small.
__We obtain the correct `b/(b+i)` when using the new reciprocal scaling algorithm. Note that, in finite single precision, `b/(b+i)` rounds up to `1 - i/b`, not to `1`.__

2. Now, let me we try the matrix:
```
b+I b
  b b
```
The condition number here is awful, larger than 2b. In this case, LAPACK's getf2 returns the factorization:
```
b+I b
  1 0
```
We still have a small relative error. However, the LU factorization returns a singular matrix since there is a 0 in the diagonal of U. If we try to solve a linear system we may end up in a division by zero which raises an exception.

The correct LU factorization is 
```
    b+I b
b/(b+i) I
```
which is the one we obtain by using the algorithm I propose in this PR.

**Pull request merged**
