### PR TITLE
Multishift qr with aed

### PR DESCRIPTION
**Pull request by thijssteel**
Adds multishift QR with AED

Tests aren't fully complete, but I'll add those in a separate PR ( so I can use my other test improvement PR).

I haven't done performance tests, can't get MKL to work. @weslleyspereira maybe you can do some performance tests if you can spare an hour some day.

### CODE REVIEW

**Comment by thijssteel** [comment]
starting to dislike catch2.

The tests pass when using `./tester "Multishift QR - types_to_test - 4"`, but fail when running them all using `./tester`.
I've gotten no response about my bug report from a week ago. Maybe julien had a point when he advocated for a simple test script

**Comment by thijssteel** [comment]
It took me a while, but this should now be fully ready for review. The PR now contains:

- multishift qr
- bug fixes in hessenberg reduction
- bug fixes in double shift qr
- thorough tests
- new testing utils

**Comment by thijssteel** [comment]
Some performance tests:

```
run< float >( 1000 )
Hessenberg time = +0.57083 s
Q forming time = +0.35488 s
QR time = +1.19742 s
||QHQ* - A||_F/||A||_F  = +0.00001,        ||Q'Q - I||_F  = +0.00027
-----------------------
run< std::complex<float>  >( 1000 )
Hessenberg time = +3.13579 s
Q forming time = +1.22431 s
QR time = +7.69650 s
||QHQ* - A||_F/||A||_F  = +0.00000,        ||Q'Q - I||_F  = +0.00019
-----------------------
run< double >( 1000 )
Hessenberg time = +0.90581 s
Q forming time = +0.47806 s
QR time = +2.67170 s
||QHQ* - A||_F/||A||_F  = +0.00000,        ||Q'Q - I||_F  = +0.00000
-----------------------
run< std::complex<double>  >( 1000 )
Hessenberg time = +3.13460 s
Q forming time = +1.27966 s
QR time = +10.60931 s
||QHQ* - A||_F/||A||_F  = +0.00000,        ||Q'Q - I||_F  = +0.00000
```

pretty reasonable timings for the real matrices, but the complex codes are all very slow

**Comment by langou** [comment]
> pretty reasonable timings for the real matrices, but the complex codes are all very slow

To explain the timing, we probably need to look at a combination of data movement, cost of operations, and where the operations are being performed (vector unit or x86).

If we compare real<double> over real<float>, we get [ 1.7x  1.4x  2.3x ], so about 2x, so this seems to indicate that the compiler is able to take advantage of vector instructions for real arithmetic. (Time of a double operation is 2x as time of a float operation.) 

If we compare complex<double> over complex<float>, we get [ 1.0x 1.0x 1.4x ], so about 1x, so this seems to indicate that the compiler is not able to take advantage of vector instructions for complex arithmetic and operations are done using x86 instructions. (Time of a double operation is same as time of a single operation.) Which kind of make sense. I am not sure compilers are able to take advantage of vector instructions in complex for a complex multiplication. It seems complicated to get the compiler to do this.

If we compare complex<float> over real<float>, we get [ 5.5x 3.5x 6.5x ], so about 6x. If we compare complex<double> over real<double>, we get [ 3.1x 2.6x 4.1x ],  so about 3x. We do 6 operations for a complex multiplication of the type (a,b)*(c,d)=(a*c-b*d,b*c+a*d). This 6x does not take into account the fact that real arithmetic could be done on vector instructions and complex arithmetic could be done on x86 instructions. 

Moving complex numbers to cache is 2x more time than moving real numbers.

**Comment by thijssteel** [comment]
Some profiling results for floats:

Note that the cpp code uses significantly more shifts. The speedup of the fortran code is roughly the same as the decrease in the amount of shifts. So if we fix that, we will likely get good performance.

`
run< float >( 1000 ) without LAPACK 

Hessenberg time = +1.02398e-01 s
Q forming time = +3.01702e-02 s
QR time = +3.24507e-01 s
||QHQ* - A||_F/||A||_F  = +6.08869e-06,        ||Q'Q - I||_F  = +2.23739e-04
AED calls   +38
Sweep calls +9
Shifts used +576

-----------------------
run< float >( 1000 ) with LAPACK 

Hessenberg time = +7.02545e-02 s
Q forming time = +1.78728e-02 s
QR time = +2.91919e-01 s
||QHQ* - A||_F/||A||_F  = +1.14170e-05,        ||Q'Q - I||_F  = +3.83774e-04
AED calls   +41
Sweep calls +6
Shifts used +384

-----------------------

run< float >( 2000 ) without LAPACK 

Hessenberg time = +6.95691e-01 s
Q forming time = +1.16392e-01 s
QR time = +1.08132e+00 s
||QHQ* - A||_F/||A||_F  = +7.93728e-06,        ||Q'Q - I||_F  = +4.02950e-04
AED calls   +82
Sweep calls +16
Shifts used +1024

-----------------------
run< float >( 2000 ) with LAPACK 

Hessenberg time = +7.60112e-01 s
Q forming time = +1.11531e-01 s
QR time = +8.75334e-01 s
||QHQ* - A||_F/||A||_F  = +1.43362e-05,        ||Q'Q - I||_F  = +6.73051e-04
AED calls   +81
Sweep calls +13
Shifts used +832

-----------------------

run< float >( 4000 ) without LAPACK 

Hessenberg time = +6.13212e+00 s
Q forming time = +7.01477e-01 s
QR time = +6.49799e+00 s
||QHQ* - A||_F/||A||_F  = +1.49774e-05,        ||Q'Q - I||_F  = +1.00199e-03
AED calls   +83
Sweep calls +11
Shifts used +1408

-----------------------
run< float >( 4000 ) with LAPACK 

Hessenberg time = +6.94183e+00 s
Q forming time = +6.93725e-01 s
QR time = +4.60176e+00 s
||QHQ* - A||_F/||A||_F  = +2.86779e-05,        ||Q'Q - I||_F  = +1.87223e-03
AED calls   +77
Sweep calls +8
Shifts used +1024

-----------------------
`

**Pull request merged**
