### PR TITLE
PTTRF implementation

### PR DESCRIPTION
**Pull request by hmk46**

### CODE REVIEW

**Comment by weslleyspereira** [comment]
Great!! Your contribution looks super clean! Let me just see if all the tests pass before merging.

**Comment by hmk46** [comment]
Looks like the failing test is an unrelated lapack++ build issue:

```
-- Looking for LAPACK libraries and options
   /home/runner/work/tlapack/tlapack/lapack/lib/liblapack.a;-lgfortran  no (didn't run: int mismatch, etc.)
   LAPACK library not found.
CMake Error at CMakeLists.txt:662 (message):
  LAPACK++ requires a LAPACK library and none was found.  Ensure that it is
  accessible in environment variables $CPATH, $LIBRARY_PATH, and
  $LD_LIBRARY_PATH.
```

**Comment by weslleyspereira** [comment]
> Looks like the failing check is an unrelated lapack++ build issue:
> 
> ```
> -- Looking for LAPACK libraries and options
>    /home/runner/work/tlapack/tlapack/lapack/lib/liblapack.a;-lgfortran  no (didn't run: int mismatch, etc.)
>    LAPACK library not found.
> CMake Error at CMakeLists.txt:662 (message):
>   LAPACK++ requires a LAPACK library and none was found.  Ensure that it is
>   accessible in environment variables $CPATH, $LIBRARY_PATH, and
>   $LD_LIBRARY_PATH.
> ```

Yes, you are right. This error occurs frequently and I actually don't know exactly why.

**Comment by weslleyspereira** [comment]
Thanks for this first (and great) contribution!

**Pull request merged**
